// This file is automatically generated. Do not edit it directly.
import type { Database } from './types';

type MockUser = {
  id: string;
  email: string;
  user_metadata: {
    full_name?: string;
  };
};

type MockSession = {
  user: MockUser;
  access_token: string;
};

type MockError = {
  message: string;
};

type MockResponse<T> = {
  data: T | null;
  error: MockError | null;
};

type MockQueryResult = {
  then: (callback: (result: MockResponse<unknown>) => void) => void;
};

type MockOrderBuilder = {
  limit: (limit: number) => MockQueryResult;
  then: (callback: (result: MockResponse<unknown>) => void) => void;
};

type MockSelectBuilder = {
  eq: (column: string, value: string) => { maybeSingle: () => Promise<MockResponse<unknown>> };
  order: (column: string, options?: unknown) => MockOrderBuilder;
};

type MockFromBuilder = {
  select: (columns: string) => MockSelectBuilder & {
    insert: (data: unknown) => { then: (callback: (result: MockResponse<unknown>) => void) => void };
    update: (data: unknown) => { eq: (column: string, value: string) => { then: (callback: (result: MockResponse<unknown>) => void) => void } };
  };
};

type MockChannel = {
  handlers: Array<{ event: string; config: unknown; callback: (payload: unknown) => void }>;
  on: (event: string, config: unknown, callback: (payload: unknown) => void) => MockChannel;
  subscribe: () => { unsubscribe: () => void };
};

type MockDb = {
  profiles: Array<{ id: string; full_name: string; email: string; reward_points: number; free_washes: number }>;
  bookings: Array<Record<string, unknown>>;
  notifications: Array<Record<string, unknown>>;
  user_roles: Array<{ user_id: string; role: string }>;
};

const STORAGE_KEY = 'mock_db';
const ADMIN_EMAIL = 'seroganyanemathaba@gmail.com';
const ADMIN_PASSWORD = 'Ponagalo#2026';

const DEFAULT_DB: MockDb = {
  profiles: [
    { id: '1', full_name: 'John Doe', email: 'john@example.com', reward_points: 100, free_washes: 2 },
    { id: '2', full_name: 'Jane Smith', email: 'jane@example.com', reward_points: 50, free_washes: 1 }
  ],
  bookings: [],
  notifications: [],
  user_roles: [{ user_id: 'admin-user-id', role: 'admin' }]
};

const getNow = () => new Date().toISOString();

class MockSupabaseClient {
  private db: MockDb;

  constructor() {
    this.db = this.loadDb();
  }

  private loadDb(): MockDb {
    const raw = localStorage.getItem(STORAGE_KEY);
    if (!raw) {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(DEFAULT_DB));
      return JSON.parse(JSON.stringify(DEFAULT_DB));
    }
    try {
      return JSON.parse(raw) as MockDb;
    } catch {
      localStorage.setItem(STORAGE_KEY, JSON.stringify(DEFAULT_DB));
      return JSON.parse(JSON.stringify(DEFAULT_DB));
    }
  }

  private saveDb() {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(this.db));
  }

  private ensureProfileForUser(user: MockUser) {
    const exists = this.db.profiles.some((profile) => profile.id === user.id);
    if (!exists) {
      this.db.profiles.push({
        id: user.id,
        email: user.email,
        full_name: user.user_metadata.full_name || user.email.split('@')[0],
        reward_points: 0,
        free_washes: 0
      });
      this.saveDb();
    }
  }

  private getTable(table: string): Array<Record<string, unknown>> {
    return (this.db as any)[table] ?? [];
  }

  private setTable(table: string, rows: Array<Record<string, unknown>>) {
    (this.db as any)[table] = rows;
    this.saveDb();
  }

  private buildQuery(table: string, columns: string) {
    const filters: Array<{ column: string; value: string }> = [];
    let orderColumn: string | null = null;
    let orderAscending = true;

    const applyFilters = (rows: Array<Record<string, unknown>>) => {
      return rows.filter((row) => filters.every((filter) => String(row[filter.column]) === filter.value));
    };

    const applyOrder = (rows: Array<Record<string, unknown>>) => {
      if (!orderColumn) return rows;
      return [...rows].sort((a, b) => {
        const aValue = String(a[orderColumn] ?? '');
        const bValue = String(b[orderColumn] ?? '');
        if (aValue === bValue) return 0;
        return orderAscending ? aValue.localeCompare(bValue) : bValue.localeCompare(aValue);
      });
    };

    const resolve = () => {
      const rows = applyFilters(this.getTable(table));
      return applyOrder(rows);
    };

    const query: any = {
      eq: (column: string, value: string) => {
        filters.push({ column, value });
        return query;
      },
      order: (column: string, options?: unknown) => {
        orderColumn = column;
        if (options && typeof options === 'object' && 'ascending' in (options as any)) {
          orderAscending = (options as any).ascending !== false;
        }
        return orderBuilder;
      },
      maybeSingle: async (): Promise<MockResponse<unknown>> => {
        const rows = resolve();
        return { data: rows[0] ?? null, error: null };
      },
      then: (callback: (result: MockResponse<unknown>) => void) => {
        const rows = resolve();
        callback({ data: rows, error: null });
      }
    };

    const orderBuilder: MockOrderBuilder = {
      limit: (limit: number) => ({
        then: (callback: (result: MockResponse<unknown>) => void) => {
          const rows = resolve().slice(0, limit);
          callback({ data: rows, error: null });
        }
      }),
      then: (callback: (result: MockResponse<unknown>) => void) => {
        const rows = resolve();
        callback({ data: rows, error: null });
      }
    };

    return query;
  }

  auth = {
    signInWithPassword: async (credentials: { email: string; password: string }) => {
      const { email, password } = credentials;
      let mockUser: MockUser;
      let mockSession: MockSession;

      if (email === ADMIN_EMAIL && password === ADMIN_PASSWORD) {
        mockUser = { id: 'admin-user-id', email: ADMIN_EMAIL, user_metadata: { full_name: 'Admin User' } };
        mockSession = { user: mockUser, access_token: 'mock-admin-token' };
      } else {
        mockUser = { id: `user-${Date.now()}`, email, user_metadata: { full_name: email.split('@')[0] } };
        mockSession = { user: mockUser, access_token: 'mock-user-token' };
      }

      this.ensureProfileForUser(mockUser);
      localStorage.setItem('mock_session', JSON.stringify(mockSession));
      window.dispatchEvent(new StorageEvent('storage', {
        key: 'mock_session',
        oldValue: null,
        newValue: JSON.stringify(mockSession),
        storageArea: localStorage
      }));

      return { data: { user: mockUser, session: mockSession }, error: null };
    },

    signUp: async (credentials: { email: string; password: string; options?: { data?: { full_name?: string } } }) => {
      const { email, options } = credentials;
      const mockUser: MockUser = {
        id: `user-${Date.now()}`,
        email,
        user_metadata: { full_name: options?.data?.full_name || email.split('@')[0] }
      };
      const mockSession: MockSession = { user: mockUser, access_token: 'mock-signup-token' };

      this.ensureProfileForUser(mockUser);
      localStorage.setItem('mock_session', JSON.stringify(mockSession));
      window.dispatchEvent(new StorageEvent('storage', {
        key: 'mock_session',
        oldValue: null,
        newValue: JSON.stringify(mockSession),
        storageArea: localStorage
      }));

      return { data: { user: mockUser, session: mockSession }, error: null };
    },

    signOut: async () => {
      const oldValue = localStorage.getItem('mock_session');
      localStorage.removeItem('mock_session');
      window.dispatchEvent(new StorageEvent('storage', {
        key: 'mock_session',
        oldValue,
        newValue: null,
        storageArea: localStorage
      }));
      return { error: null };
    },

    getSession: async () => {
      const savedSession = localStorage.getItem('mock_session');
      if (savedSession) {
        try {
          const parsedSession = JSON.parse(savedSession);
          return { data: { session: parsedSession }, error: null };
        } catch {
          return { data: { session: null }, error: null };
        }
      }
      return { data: { session: null }, error: null };
    },

    getUser: async () => {
      const savedSession = localStorage.getItem('mock_session');
      if (savedSession) {
        try {
          const parsedSession = JSON.parse(savedSession);
          return { data: { user: parsedSession.user }, error: null };
        } catch {
          return { data: { user: null }, error: null };
        }
      }
      return { data: { user: null }, error: null };
    },

    onAuthStateChange: (callback: (event: string, session: MockSession | null) => void) => {
      const checkAuth = () => {
        const savedSession = localStorage.getItem('mock_session');
        if (savedSession) {
          try {
            const session = JSON.parse(savedSession) as MockSession;
            callback('SIGNED_IN', session);
          } catch {
            callback('SIGNED_OUT', null);
          }
        } else {
          callback('SIGNED_OUT', null);
        }
      };

      checkAuth();
      const handleStorageChange = (e: StorageEvent) => {
        if (e.key === 'mock_session') {
          checkAuth();
        }
      };
      window.addEventListener('storage', handleStorageChange);
      return {
        data: {
          subscription: {
            unsubscribe: () => window.removeEventListener('storage', handleStorageChange)
          }
        }
      };
    }
  };

  from = (table: string) => {
    const queryBuilder = {
      select: (columns: string) => {
        const query = this.buildQuery(table, columns);
        return {
          ...query,
          insert: (data: unknown) => Promise.resolve(this.insertData(table, data)),
          update: (data: unknown) => ({
            eq: (column: string, value: string) => Promise.resolve(this.updateData(table, data, column, value))
          })
        };
      },
      insert: (data: unknown) => Promise.resolve(this.insertData(table, data)),
      update: (data: unknown) => ({
        eq: (column: string, value: string) => Promise.resolve(this.updateData(table, data, column, value))
      })
    };
    return queryBuilder;
  };

  private insertData(table: string, data: unknown): MockResponse<unknown> {
    const rows = Array.isArray(data) ? data : [data];
    const savedRows = this.getTable(table);
    const inserted = rows.map((row: any) => {
      const id = row?.id || `${table}-${Date.now()}-${Math.random().toString(36).slice(2)}`;
      const now = getNow();
      return {
        ...row,
        id,
        created_at: row?.created_at || now,
        updated_at: row?.updated_at || now
      };
    });
    this.setTable(table, [...savedRows, ...inserted]);
    return { data: inserted, error: null };
  }

  private updateData(table: string, data: unknown, column: string, value: string): MockResponse<unknown> {
    const rows = this.getTable(table);
    const updated: Array<Record<string, unknown>> = [];
    const newRows = rows.map((row) => {
      if (String(row[column]) === value) {
        const next = { ...row, ...data, updated_at: getNow() } as Record<string, unknown>;
        updated.push(next);
        return next;
      }
      return row;
    });
    this.setTable(table, newRows);
    return { data: updated.length > 0 ? updated : null, error: null };
  }

  rpc = (functionName: string) => ({
    then: (callback: (result: MockResponse<unknown>) => void) => {
      callback({ data: null, error: null });
    }
  });

  channel = (name: string): MockChannel => {
    const channelObj: MockChannel = {
      handlers: [],
      on(event: string, config: unknown, callback: (payload: unknown) => void) {
        this.handlers.push({ event, config, callback });
        return this;
      },
      subscribe() {
        return {
          unsubscribe: () => {}
        };
      }
    };
    return channelObj;
  };

  removeChannel = (channel: { unsubscribe?: () => void } | null) => {
    if (channel?.unsubscribe) {
      channel.unsubscribe();
    }
  };
}

// Use mock client instead of real Supabase client
export const supabase = new MockSupabaseClient();